#include<stdio.h>
int main(void)
{
    long int n[10000];
    int i=0;
    while(scanf("%ld",&n[0])!=EOF)
    {
        printf("Hailstone generated by %ld:\n",n[0]);
        printf("%ld",n[i]);
        while(n[i]!=1)
        {
          if(n[i]%2==0)
            {
                n[i+1]=n[i]/2;
          printf("% ld",n[i+1]);
          i+=1;
            }
          else if(n[i]%2)
          {
              n[i+1]=3*n[i]+1;
              printf(" %ld ",n[i+1]);
              i+=1;
          }
        }
        printf("\n");
        printf("Number of hailstone generated:%d\n",i+1);
        printf("\n");
        i=0;
    }
    return 0;

}
